manifest_version = 2
name = "Add a new field to a JSON response"
description = ""
authors = ["<oss@fastly.com>"]
language = "assemblyscript"

[local_server.backends.origin_0]
      url = "https://httpbin.org"

[setup.backends.origin_0]
address = "httpbin.org"
port = 443
